# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1405, 847)
        Dialog.setAutoFillBackground(False)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 1416, 700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        spacerItem = QtWidgets.QSpacerItem(103, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.minDepth = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.minDepth.setProperty("value", 0.6)
        self.minDepth.setObjectName("minDepth")
        self.horizontalLayout_11.addWidget(self.minDepth)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.maxDepth = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.maxDepth.setProperty("value", 0.85)
        self.maxDepth.setObjectName("maxDepth")
        self.horizontalLayout_12.addWidget(self.maxDepth)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        spacerItem4 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.pathTime = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.pathTime.setProperty("value", 0.6)
        self.pathTime.setObjectName("pathTime")
        self.horizontalLayout_13.addWidget(self.pathTime)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        spacerItem6 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.camSN = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camSN.sizePolicy().hasHeightForWidth())
        self.camSN.setSizePolicy(sizePolicy)
        self.camSN.setObjectName("camSN")
        self.horizontalLayout_14.addWidget(self.camSN)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        spacerItem8 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.robotCamSN = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotCamSN.sizePolicy().hasHeightForWidth())
        self.robotCamSN.setSizePolicy(sizePolicy)
        self.robotCamSN.setText("")
        self.robotCamSN.setObjectName("robotCamSN")
        self.horizontalLayout_15.addWidget(self.robotCamSN)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_15.addWidget(self.checkBox_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 5, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 1, 3, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 1, 1, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 3, 3, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.motor_x_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_x_min.setDecimals(3)
        self.motor_x_min.setMinimum(-100.0)
        self.motor_x_min.setMaximum(100.0)
        self.motor_x_min.setProperty("value", 0.185)
        self.motor_x_min.setObjectName("motor_x_min")
        self.horizontalLayout_21.addWidget(self.motor_x_min)
        self.motor_x_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_x_max.setDecimals(3)
        self.motor_x_max.setMinimum(-100.0)
        self.motor_x_max.setMaximum(100.0)
        self.motor_x_max.setProperty("value", 99.0)
        self.motor_x_max.setObjectName("motor_x_max")
        self.horizontalLayout_21.addWidget(self.motor_x_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 1, 5, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 3, 2, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 1, 2, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.floor_z_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.floor_z_min.setMinimum(-100.0)
        self.floor_z_min.setMaximum(100.0)
        self.floor_z_min.setProperty("value", -99.0)
        self.floor_z_min.setObjectName("floor_z_min")
        self.horizontalLayout_22.addWidget(self.floor_z_min)
        self.floor_z_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.floor_z_max.setDecimals(3)
        self.floor_z_max.setMinimum(-100.0)
        self.floor_z_max.setMaximum(100.0)
        self.floor_z_max.setProperty("value", 0.035)
        self.floor_z_max.setObjectName("floor_z_max")
        self.horizontalLayout_22.addWidget(self.floor_z_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 4, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.motor_y_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_y_min.setDecimals(3)
        self.motor_y_min.setMinimum(-100.0)
        self.motor_y_min.setMaximum(100.0)
        self.motor_y_min.setProperty("value", -0.12)
        self.motor_y_min.setObjectName("motor_y_min")
        self.horizontalLayout_30.addWidget(self.motor_y_min)
        self.motor_y_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_y_max.setDecimals(3)
        self.motor_y_max.setMinimum(-100.0)
        self.motor_y_max.setMaximum(100.0)
        self.motor_y_max.setProperty("value", 0.05)
        self.motor_y_max.setObjectName("motor_y_max")
        self.horizontalLayout_30.addWidget(self.motor_y_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_30, 2, 5, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.outerCylinder_r_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.outerCylinder_r_min.setDecimals(3)
        self.outerCylinder_r_min.setMinimum(-100.0)
        self.outerCylinder_r_min.setMaximum(100.0)
        self.outerCylinder_r_min.setProperty("value", 0.386)
        self.outerCylinder_r_min.setObjectName("outerCylinder_r_min")
        self.horizontalLayout_28.addWidget(self.outerCylinder_r_min)
        self.outerCylinder_r_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.outerCylinder_r_max.setDecimals(3)
        self.outerCylinder_r_max.setMinimum(-100.0)
        self.outerCylinder_r_max.setMaximum(100.0)
        self.outerCylinder_r_max.setProperty("value", 99.0)
        self.outerCylinder_r_max.setObjectName("outerCylinder_r_max")
        self.horizontalLayout_28.addWidget(self.outerCylinder_r_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 2, 4, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.gridLayout_2.addLayout(self.horizontalLayout_29, 3, 4, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ceiling_z_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.ceiling_z_min.setDecimals(3)
        self.ceiling_z_min.setMinimum(-100.0)
        self.ceiling_z_min.setMaximum(100.0)
        self.ceiling_z_min.setProperty("value", 0.456)
        self.ceiling_z_min.setObjectName("ceiling_z_min")
        self.horizontalLayout_24.addWidget(self.ceiling_z_min)
        self.ceiling_z_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.ceiling_z_max.setDecimals(3)
        self.ceiling_z_max.setMinimum(-100.0)
        self.ceiling_z_max.setMaximum(100.0)
        self.ceiling_z_max.setProperty("value", 99.0)
        self.ceiling_z_max.setObjectName("ceiling_z_max")
        self.horizontalLayout_24.addWidget(self.ceiling_z_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 2, 2, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_20.addWidget(self.label_30)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 1, 4, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.innerCylinder_r_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.innerCylinder_r_min.setDecimals(3)
        self.innerCylinder_r_min.setMinimum(-100.0)
        self.innerCylinder_r_min.setMaximum(100.0)
        self.innerCylinder_r_min.setObjectName("innerCylinder_r_min")
        self.horizontalLayout_26.addWidget(self.innerCylinder_r_min)
        self.innerCylinder_r_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.innerCylinder_r_max.setDecimals(3)
        self.innerCylinder_r_max.setMinimum(-100.0)
        self.innerCylinder_r_max.setMaximum(100.0)
        self.innerCylinder_r_max.setProperty("value", 0.06)
        self.innerCylinder_r_max.setObjectName("innerCylinder_r_max")
        self.horizontalLayout_26.addWidget(self.innerCylinder_r_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_26, 2, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.motor_z_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_z_min.setDecimals(3)
        self.motor_z_min.setMinimum(-100.0)
        self.motor_z_min.setMaximum(100.0)
        self.motor_z_min.setProperty("value", -99.0)
        self.motor_z_min.setObjectName("motor_z_min")
        self.horizontalLayout_31.addWidget(self.motor_z_min)
        self.motor_z_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.motor_z_max.setDecimals(3)
        self.motor_z_max.setMinimum(-100.0)
        self.motor_z_max.setMaximum(100.0)
        self.motor_z_max.setProperty("value", 0.095)
        self.motor_z_max.setObjectName("motor_z_max")
        self.horizontalLayout_31.addWidget(self.motor_z_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_31, 3, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.gridLayout.addLayout(self.verticalLayout, 8, 5, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.threshold_thumbAngle2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.threshold_thumbAngle2.setMinimum(-180.0)
        self.threshold_thumbAngle2.setMaximum(180.0)
        self.threshold_thumbAngle2.setProperty("value", -15.0)
        self.threshold_thumbAngle2.setObjectName("threshold_thumbAngle2")
        self.horizontalLayout_4.addWidget(self.threshold_thumbAngle2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.threshold_thumbAngle2_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.threshold_thumbAngle2_2.setMinimum(-180.0)
        self.threshold_thumbAngle2_2.setMaximum(180.0)
        self.threshold_thumbAngle2_2.setProperty("value", -15.0)
        self.threshold_thumbAngle2_2.setObjectName("threshold_thumbAngle2_2")
        self.horizontalLayout_3.addWidget(self.threshold_thumbAngle2_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.threshol_fingerAngle1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.threshol_fingerAngle1.setMaximum(180.0)
        self.threshol_fingerAngle1.setProperty("value", 25.0)
        self.threshol_fingerAngle1.setObjectName("threshol_fingerAngle1")
        self.horizontalLayout_2.addWidget(self.threshol_fingerAngle1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.threshold_fingerAngle2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.threshold_fingerAngle2.setMaximum(180.0)
        self.threshold_fingerAngle2.setProperty("value", 25.0)
        self.threshold_fingerAngle2.setObjectName("threshold_fingerAngle2")
        self.horizontalLayout.addWidget(self.threshold_fingerAngle2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.K_p_psi = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.K_p_psi.setProperty("value", 0.2)
        self.K_p_psi.setObjectName("K_p_psi")
        self.horizontalLayout_5.addWidget(self.K_p_psi)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.K_p_r = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.K_p_r.setProperty("value", 0.05)
        self.K_p_r.setObjectName("K_p_r")
        self.horizontalLayout_6.addWidget(self.K_p_r)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.K_p_z = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.K_p_z.setProperty("value", 0.07)
        self.K_p_z.setObjectName("K_p_z")
        self.horizontalLayout_7.addWidget(self.K_p_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.K_p_theta = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.K_p_theta.setProperty("value", 0.15)
        self.K_p_theta.setObjectName("K_p_theta")
        self.horizontalLayout_8.addWidget(self.K_p_theta)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.K_p_phi = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.K_p_phi.setProperty("value", 10.0)
        self.K_p_phi.setObjectName("K_p_phi")
        self.horizontalLayout_9.addWidget(self.K_p_phi)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.gridLayout.addLayout(self.verticalLayout_2, 8, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 7, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 9, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 8, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 8, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 11, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 8, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 8, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 8, 7, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 8, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Environment</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>Min depth</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>Max depth</p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p>Path time</p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Camera</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>Operator Cam S/N</p></body></html>"))
        self.camSN.setText(_translate("Dialog", "836612072676"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p>Robot Cam S/N</p></body></html>"))
        self.checkBox_2.setText(_translate("Dialog", "Active"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Obstacles</span></p></body></html>"))
        self.label_29.setText(_translate("Dialog", "Motor [x, y, z]"))
        self.label_23.setText(_translate("Dialog", "Floor"))
        self.label_25.setText(_translate("Dialog", "Radius range"))
        self.label_21.setText(_translate("Dialog", "Z range"))
        self.label_24.setText(_translate("Dialog", "Z range"))
        self.label_28.setText(_translate("Dialog", "Outer Cylinder"))
        self.label_30.setText(_translate("Dialog", "Radius range"))
        self.label_27.setText(_translate("Dialog", "Inner Cylinder"))
        self.label_26.setText(_translate("Dialog", "Ceiling"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Thumb</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>α<span style=\" vertical-align:sub;\">1</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>α<span style=\" vertical-align:sub;\">2</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Fingers</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>α<span style=\" vertical-align:sub;\">1</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>α<span style=\" vertical-align:sub;\">2</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Controller</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">p</span><span style=\" vertical-align:super;\">&psi;</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">p</span><span style=\" vertical-align:super;\">r</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">p</span><span style=\" vertical-align:super;\">z</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">p</span><span style=\" vertical-align:super;\">&theta;</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">p</span><span style=\" vertical-align:super;\">&phi;</span></p></body></html>"))

